apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudmart.componentName" (dict "component" "product-service" "context" .) }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudmart.componentLabels" (dict "component" "product-service" "context" .) | nindent 4 }}
data:
  REDIS_URL: "redis://{{ include "cloudmart.componentName" (dict "component" "redis" "context" .) }}-service:6379"
