apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudmart.componentName" (dict "component" "product-service" "context" .) }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudmart.componentLabels" (dict "component" "product-service" "context" .) | nindent 4 }}
spec:
  replicas: {{ .Values.productService.replicas }}
  selector:
    matchLabels:
      {{- include "cloudmart.componentSelectorLabels" (dict "component" "product-service" "context" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudmart.componentSelectorLabels" (dict "component" "product-service" "context" .) | nindent 8 }}
    spec:
      containers:
        - name: product-service
          image:  "{{ .Values.productService.image.repository }}:{{ .Values.productService.image.tag }}"
          imagePullPolicy: {{ .Values.productService.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: cloudmart-product-service-secret
            - configMapRef:
                name: {{ include "cloudmart.componentName" (dict "component" "product-service" "context" .) }}-configmap
          resources:
            {{- toYaml .Values.productService.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
