{{- if .Values.productService.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cloudmart.componentName" (dict "component" "product-service" "context" .) }}-hpa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudmart.componentLabels" (dict "component" "product-service" "context" .) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cloudmart.componentName" (dict "component" "product-service" "context" .) }}-deployment
  minReplicas: {{ .Values.productService.hpa.minReplicas }}
  maxReplicas: {{ .Values.productService.hpa.maxReplicas }}
  metrics:
    {{- if .Values.productService.hpa.cpu.enabled }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.productService.hpa.cpu.targetAverageUtilization }}
    {{- end }}
    {{- if .Values.productService.hpa.memory.enabled }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.productService.hpa.memory.targetAverageUtilization }}
    {{- end }}
{{- end }}
