apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: cloudmart-monitoring
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    admin-password: AgAj3tF60vMN1GfmL7CKG/aCyuP+E3GxIPLZrNodgVb4q5OBvB9ZnnzjkHvf4wjYosZVVvdFrb3NRsirdl/J2ps8Cj1ND/yD9foKh6xeMvXtVse6BukYUZ88lsYLd1oFifnZhOnX7eFxKu0K811dTiVHgdLpqQ0u+B3bGHGKHyMDuwOZdmcn3ZSY1K0Yjiu5zaVM6T6pN6DbYPSEGJkORtSW5NfwL6msD46qrxA43Yz1Z35MhvVmiz6ePyLwQfL2LH0KqQNKSBuQb3E8BEaRKZg08y/WAHLqan3+Qv37+ivHFl7XqXl+M9E1HzAWRvPRthwzip+jtXJsSP1tnSl7CyLG/QMXBp8LiXt3Q10vWO0oGvsO1wInULCjh3w57rzFehMYH5No4BAAVihfutScbYmFlqJMBGGKwMRLg7EmL+8OlRM+R73zwE51M6hWHtp/j9ILTfLQ8/92GnjI0CkS8WpK+oDprKREejLU6TFt9sCddPNHuuqTFjgbtRGiVv3Z9b/fIejvbWYq1lpyKS4AkR5rBiwr7Be+yDudFB7cH4geE/f1+m30DUWwf511N6XJrQGYQL4/HFFn9ahRA40Lng1FPhfXiPGTkGXsh6tJgHzr79Hc+7nYBTiif4um9Q/yMhMg3WbnfYbV/hvg1orT9cxjtttpNJKk4jeO+wcKxmR38RRPveZuH76CCnQsAGFaQUXlmTmQ4mfhrPLf
  template:
    metadata:
      name: grafana-admin-secret
    type: Opaque
