apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudmart.componentName" (dict "component" "order-service" "context" .) }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudmart.componentLabels" (dict "component" "order-service" "context" .) | nindent 4 }}
spec:
  replicas: {{ .Values.orderService.replicas }}
  selector:
    matchLabels:
      {{- include "cloudmart.componentSelectorLabels" (dict "component" "order-service" "context" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudmart.componentSelectorLabels" (dict "component" "order-service" "context" .) | nindent 8 }}
    spec:
      containers:
        - name: order-service
          image: "{{ .Values.orderService.image.repository }}:{{ .Values.orderService.image.tag }}"
          imagePullPolicy: {{ .Values.orderService.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-order-service-secret
          resources:
            {{- toYaml .Values.orderService.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
