{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-jwt-secret
  namespace: {{ .Values.namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app.kubernetes.io/name: jwt-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: sealed-secret
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "cloudmart.chart" . }}
spec:
  encryptedData:
    JWT_SECRET: {{ .Values.sealedSecrets.jwt.JWT_SECRET }}
  template:
    metadata:
      name: {{ .Release.Name }}-jwt-secret
      namespace: {{ .Values.namespace }}
    type: Opaque
{{- end }}
