{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-postgres-database-secret
  namespace: {{ .Values.namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app.kubernetes.io/name: postgres-database-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: sealed-secret
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "cloudmart.chart" . }}
spec:
  encryptedData:
    POSTGRES_USER: {{ .Values.sealedSecrets.postgres.POSTGRES_USER }}
    POSTGRES_PASSWORD: {{ .Values.sealedSecrets.postgres.POSTGRES_PASSWORD }}
  template:
    metadata:
      name: {{ .Release.Name }}-postgres-database-secret
      namespace: {{ .Values.namespace }}
    type: Opaque
{{- end }}
