apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudmart.componentName" (dict "component" "user-service" "context" .) }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudmart.componentLabels" (dict "component" "user-service" "context" .) | nindent 4 }}
spec:
  replicas: {{ .Values.userService.replicas }}
  selector:
    matchLabels:
      {{- include "cloudmart.componentSelectorLabels" (dict "component" "user-service" "context" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudmart.componentSelectorLabels" (dict "component" "user-service" "context" .) | nindent 8 }}
    spec:
      containers:
        - name: user-service
          image: "{{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}"
          imagePullPolicy: {{ .Values.userService.image.pullPolicy }}
          ports:
            - containerPort: 3001
          envFrom:
            - secretRef:
                name: cloudmart-user-service-secret
            - secretRef:
                name: cloudmart-jwt-secret
          resources:
            {{- toYaml .Values.userService.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
