apiVersion: v1
kind: Service
metadata:
  name: cloudmart-user-service-service
  namespace: {{ .Values.namespace }}
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: {{ .Values.userService.service.port }}
      targetPort: {{ .Values.userService.service.targetPort }}
      {{- if eq .Values.userService.service.type "NodePort" }}
      nodePort: {{ .Values.userService.service.nodePort }}
      {{- end }}
  type: {{ .Values.userService.service.type }}
