{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    {{- include "infrastructure.labels" . | nindent 4 }}
spec:
  encryptedData:
    JWT_SECRET: {{ .Values.sealedSecrets.jwt.JWT_SECRET }}
  template:
    metadata:
      name: jwt-secret
    type: Opaque
{{- end }}
