{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    {{- include "infrastructure.labels" . | nindent 4 }}
spec:
  encryptedData:
    POSTGRES_USER: {{ .Values.sealedSecrets.postgres.POSTGRES_USER }}
    POSTGRES_PASSWORD: {{ .Values.sealedSecrets.postgres.POSTGRES_PASSWORD }}
  template:
    metadata:
      name: postgres-secret
    type: Opaque
{{- end }}
