apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "infrastructure.componentLabels" (dict "component" "postgres" "context" .) | nindent 4 }}
spec:
  selector:
    {{- include "infrastructure.componentSelectorLabels" (dict "component" "postgres" "context" .) | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.targetPort }}
