apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudmart-ingress
  namespace: cloudmart-dev
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - cloudmart.local
      secretName: cloudmart-tls-secret
  rules:
    - host: cloudmart.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloudmart-api-gateway-service
                port:
                  number: 3000
