# Create actual secret with:
# kubectl create secret tls cloudmart-tls-secret \
#   --cert=certs/tls.crt \
#   --key=certs/tls.key \
#   -n cloudmart-dev

apiVersion: v1
kind: Secret
metadata:
  name: cloudmart-tls-secret
  namespace: cloudmart-dev
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-cert>
  tls.key: <base64-encoded-key>
