apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "product-service.fullname" . }}-config
  labels:
    {{- include "product-service.labels" . | nindent 4 }}
data:
  REDIS_URL: {{ .Values.config.redisUrl | quote }}
