{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: product-service-secret
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    {{- include "product-service.labels" . | nindent 4 }}
spec:
  encryptedData:
    DATABASE_URL: {{ .Values.sealedSecrets.databaseUrl }}
  template:
    metadata:
      name: product-service-secret
    type: Opaque
{{- end }}
