apiVersion: v1
kind: Secret
metadata:
  name: cloudmart-user-service-secret
  namespace: cloudmart-dev
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@cloudmart-postgres-database-service:5432/cloudmart"

