apiVersion: v1
kind: Secret
metadata:
  name: cloudmart-postgres-database-secret
  namespace: cloudmart-dev
type: Opaque
stringData:
  POSTGRES_USER: "your-username"
  POSTGRES_PASSWORD: "your-password"
