{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-to-user-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: allow-to-user-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: network-policy
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "cloudmart.chart" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "cloudmart.componentSelectorLabels" (dict "component" "user-service" "context" .) | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "cloudmart.componentSelectorLabels" (dict "component" "api-gateway" "context" .) | nindent 14 }}
      ports:
        - protocol: TCP
          port: 3001
{{- end }}
