{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-default-deny-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: default-deny-ingress
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: network-policy
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "cloudmart.chart" . }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
{{- end }}
