apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudmart.componentName" (dict "component" "postgres-database" "context" .) }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudmart.componentLabels" (dict "component" "postgres-database" "context" .) | nindent 4 }}
data:
  {{- toYaml .Values.postgres.config | nindent 2 }}
