apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloudmart.componentName" (dict "component" "postgres-database" "context" .) }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudmart.componentLabels" (dict "component" "postgres-database" "context" .) | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgres.storage.className }}
  storageClassName: {{ .Values.postgres.storage.className }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
