apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudmart-postgres-database-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgres.storage.className }}
  storageClassName: {{ .Values.postgres.storage.className }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
