apiVersion: v1
kind: Service
metadata:
  name: cloudmart-postgres-database-service
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres-database
spec:
  selector:
    app: postgres-database
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.targetPort }}
