apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cloudmart.componentName" (dict "component" "postgres-database" "context" .) }}-statefulset
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudmart.componentLabels" (dict "component" "postgres-database" "context" .) | nindent 4 }}
spec:
  serviceName: {{ include "cloudmart.componentName" (dict "component" "postgres-database" "context" .) }}-service
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      {{- include "cloudmart.componentSelectorLabels" (dict "component" "postgres-database" "context" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudmart.componentSelectorLabels" (dict "component" "postgres-database" "context" .) | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: {{ include "cloudmart.componentName" (dict "component" "postgres-database" "context" .) }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-postgres-database-secret
          volumeMounts:
            - name: cloudmart-postgres-database-volume
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)
            initialDelaySeconds: 10
            periodSeconds: 5

      volumes:
        - name: cloudmart-postgres-database-volume
          persistentVolumeClaim:
            claimName: {{ include "cloudmart.componentName" (dict "component" "postgres-database" "context" .) }}-pvc
