apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudmart.componentName" (dict "component" "redis" "context" .) }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudmart.componentLabels" (dict "component" "redis" "context" .) | nindent 4 }}
spec:
  selector:
    {{- include "cloudmart.componentSelectorLabels" (dict "component" "redis" "context" .) | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.targetPort }}
