apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudmart.componentName" (dict "component" "api-gateway" "context" .) }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudmart.componentLabels" (dict "component" "api-gateway" "context" .) | nindent 4 }}
data:
  PRODUCT_SERVICE_URL: "http://{{ include "cloudmart.componentName" (dict "component" "product-service" "context" .) }}-service:8000"
  ORDER_SERVICE_URL: "http://{{ include "cloudmart.componentName" (dict "component" "order-service" "context" .) }}-service:8080"
  USER_SERVICE_URL: "http://{{ include "cloudmart.componentName" (dict "component" "user-service" "context" .) }}-service:3001"
  REDIS_URL: "redis://{{ include "cloudmart.componentName" (dict "component" "redis" "context" .) }}-service:6379"
