apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudmart.componentName" (dict "component" "api-gateway" "context" .) }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudmart.componentLabels" (dict "component" "api-gateway" "context" .) | nindent 4 }}
spec:
  replicas: {{ .Values.apiGateway.replicas }}
  selector:
    matchLabels:
      {{- include "cloudmart.componentSelectorLabels" (dict "component" "api-gateway" "context" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudmart.componentSelectorLabels" (dict "component" "api-gateway" "context" .) | nindent 8 }}
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
          imagePullPolicy: {{ .Values.apiGateway.image.pullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ include "cloudmart.componentName" (dict "component" "api-gateway" "context" .) }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-jwt-secret
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
