apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudmart.componentName" (dict "component" "api-gateway" "context" .) }}-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudmart.componentLabels" (dict "component" "api-gateway" "context" .) | nindent 4 }}
spec:
  selector:
    {{- include "cloudmart.componentSelectorLabels" (dict "component" "api-gateway" "context" .) | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.service.targetPort }}
      {{- if eq .Values.apiGateway.service.type "NodePort" }}
      nodePort: {{ .Values.apiGateway.service.nodePort }}
      {{- end }}
  type: {{ .Values.apiGateway.service.type }}
