apiVersion: v1
kind: Service
metadata:
  name: cloudmart-api-gateway-service
  namespace: {{ .Values.namespace }}
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.service.targetPort }}
      {{- if eq .Values.apiGateway.service.type "NodePort" }}
      nodePort: {{ .Values.apiGateway.service.nodePort }}
      {{- end }}
  type: {{ .Values.apiGateway.service.type }}
