apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: cloudmart-monitoring
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    admin-user: AgBNLM1jxhNSTiBl/WvY3wLdngsqrazvIeWDSQrUJCi2N0lpZBARLL5ak3dlcLaU1OkUI+LbgjEAStMHAGq1jjJ9tDhWe16+jpNGO6jediqKOXTRFmIaQMxj84jrttBeGO9Du2wLjn2Tlj7hyD/x8y9o1sFNc8A307NvH/h31EzClRQFVUkwyynhNJ8UtsnLd8mH6RHi3g5agr5C0N1tdc2XICVxFHnn6veH2H7Z30BXDE0YUzYU0w7iUyOJg3sId92gN0mwrxubGGLAmfZVb4PW/S7GbqEKnk+3D8ZSIDlcYW3JyWJae8OiyC7oe4J1c8ECDxV2AYkckTHyjn7H/hWEbPTKwvT2fpVxugT5Z1p8bsUJPVvaIKoY65F3TsLH46PtFoaEhEBScmGOmv1a9BaZdtN9Aff8qk6x8d0fO6MJx7iFgC0azprxSbaQ46PatCZ3vIn+FynF4LHhJ/h68LUZV6BG9kwwgFQXAq4r8qtdRWWcKLAoHLQzQp+rv4RwoLrf0dLvGHuGZStXD1pg0+Yxm/O7EjQsBloUApJVqvr/HliAOkfkqV6k9Ujs+Sjy/l+wSs4slQJDTv96os6CE6oY00iLwuiDpEobKHuV/2XzvVpWt8N2pGLNmxPnLyRkFOfyk2tkU258CBgazycG3t3AGnrrxtDj7+ROXE+Kmn+fEhW/Vc/3/UJ9htd9lQeThFcdOFDMSA==
    admin-password: AgCDmBzLL5qyTATuCHdF3vvbDUf+QzlZXoZqzMj+MQce+dfHX1r+jkQYT8a1gaLdGa0vuF318bAiq1FNhOEgU0dK3cC2lw5ZVRQUU2owJMTO/SlIM4lOG0u292WSO2rrJUHTOYSicdMpuZaXTt72yJGH78egdTsVoxPTdwkBUaQEfVKIzuo+zc9CuBE8bOj0HSPGa8hDpRKvM2saJ0uhdYVi6NjnE6D1AVcSU5C1LSTdlWGkQCvaC9XddOLsgZYM5m0bzsCrZnjIGm5nVhtXdvOVMkVeVHGUtREh7cwlNLjuQbc1GQ1Wv9X6WjcFJMM9BBTPhtGdM2xnOSSmiNP0ylTwP6em01oefKXmijUuFXOWzpqWMtzPJ62U4oWpnfLstgirSw10L28einGYD6aM8rYBMMJ7rqQ7+iGsrrV1vStzfM5aN9nizyirgevILPexQuCjHnNq1+DVvA4fkTHubvejMqNZGj/jD6WaGcxVJPMVQc4NaNcTxOvzBuoD41AHNGXpF8nfiV/pISK0uX1FuLmBllBhXowKBsnpEqpcDt8LJAvbOa3bxTgXP9L20cIJSJoyAX6E9rS0DI+eoW1iQdcQ66MgpslVzF1o3Gz1/qt/dkiKSQUhkB3lVV9RJQ4iguGWaTYfGv/vUkpjtsAMcV7mcQrYPUKdC8/lHnWb2FUW22ur4fNDHapKNG/XXKW8pPayqidmO3KDxccW
  template:
    metadata:
      name: grafana-admin-secret
    type: Opaque
