name: Helm Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - 'infrastructure/kubernetes/helm/**'
  push:
    branches:
      - main
    paths:
      - 'infrastructure/kubernetes/helm/**'

env:
  CHARTS: infrastructure product-service order-service api-gateway user-service

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Lint all Helm chart
        run: |
          for chart in $CHARTS; do
            echo "=== Linting $chart ==="
            helm lint infrastructure/kubernetes/helm/$chart
          done

      - name: Template Helm chart
        run: |
          for chart in $CHARTS; do
            echo "=== Templating $chart ==="
            helm template $chart infrastructure/kubernetes/helm/$chart \
            --namespace cloudmart-dev \
            --debug
          done

      - name: Checkov IaC scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: 'infrastructure/kubernetes/helm'
          framework: 'helm'
          soft_fail: true
