name: Helm Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - 'infrastructure/kubernetes/helm/**'
  push:
    branches:
      - main
    paths:
      - 'infrastructure/kubernetes/helm/**'

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Lint Helm chart
        run: helm lint infrastructure/kubernetes/helm/cloudmart

      - name: Template Helm chart
        run: |
          helm template cloudmart infrastructure/kubernetes/helm/cloudmart \
            --namespace cloudmart-dev \
            --debug

      - name: Checkov IaC scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: 'infrastructure/kubernetes/helm/cloudmart'
          framework: 'helm'
          soft_fail: true
